name: SurvivalWerewolf
version: '${project.version}'
main: net.cherryleaves.survivalwerewolf.SurvivalWerewolf
api-version: 1.16
authors: [ sakuraba_jp ]
commands:
  startgame:
    description: start SurvivalWerewolf game.
  restartgame:
      description: restart SurvivalWerewolf game.
  stopgame:
    description: stop the game.
  resetgame:
    description: reset the game.
  job:
    description: 自分の役職を確認する。